# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-23 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poslovi',
            name='dogovoreni_radni_sati',
            field=models.FloatField(default=0.0),
        ),
    ]
