# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-23 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_poslovi_dogovoreni_radni_sati'),
    ]

    operations = [
        migrations.AddField(
            model_name='prihodi',
            name='dan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Dan'),
        ),
        migrations.AddField(
            model_name='rashodi',
            name='dan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Dan'),
        ),
    ]
